export function generateManifest(
  colors: { [key: string]: string | number },
  version: string,
) {
  const {
    purple,
    black,
    accent,
    white,
    purpleLightOne,
    purpleLightTwo,
    purpleDarkOne,
    purpleDarkTwo,
    blackLightOne,
    blackLightTwo,
  } = colors;
  const manifest = {
    manifest_version: 2,
    version: version,
    name: "Rmaki",
    theme: {
      images: {},
      properties: {},
      colors: {
        toolbar: black,
        toolbar_text: white,
        frame: blackLightTwo,
        tab_background_text: purpleDarkTwo,
        toolbar_field: blackLightTwo,
        toolbar_field_text: white,
        tab_line: accent,
        popup: blackLightTwo,
        popup_text: white,
        button_background_active: purple,
        button_background_hover: purple,
        icons_attention: white,
        icons: purpleDarkTwo,
        ntp_background: black,
        ntp_text: white,
        popup_border: purple,
        popup_highlight_text: white,
        popup_highlight: purple,
        sidebar_border: purpleDarkTwo,
        sidebar_highlight_text: white,
        sidebar_highlight: blackLightTwo,
        sidebar_text: white,
        sidebar: blackLightTwo,
        tab_background_separator: white,
        tab_text: accent,
        toolbar_bottom_separator: purple,
        toolbar_field_border_focus: white,
        toolbar_field_border: blackLightTwo,
        toolbar_field_focus: blackLightTwo,
        toolbar_field_highlight_text: black,
        toolbar_field_highlight: accent,
        toolbar_field_separator: white,
        toolbar_field_text_focus: white,
        toolbar_top_separator: blackLightTwo,
        toolbar_vertical_separator: purple,
        tab_loading: accent,
      },
    },
  };

  return manifest;
}
